// SETEAR USERS
export const SET_ROL_REQUEST = 'SET_ROL_REQUEST';
// CREATE USERS
export const CREATE_ROL_REQUEST = 'CREATE_ROL_REQUEST';
export const CREATE_ROL_RESPONSE = 'CREATE_ROL_RESPONSE';
export const CREATE_ROL_FAILED = 'CREATE_ROL_FAILED';

// UPDATE USERS
export const UPDATE_ROL_REQUEST = 'UPDATE_ROL_REQUEST';
export const UPDATE_ROL_RESPONSE = 'UPDATE_ROL_RESPONSE';
export const UPDATE_ROL_FAILED = 'UPDATE_ROL_FAILED';