// LISTA USERS
export const LISTA_DEVICE_OWNER_REQUEST = 'LISTA_DEVICE_OWNER_REQUEST';
export const LISTA_DEVICE_OWNER_RESPONSE = 'LISTA_DEVICE_OWNER_RESPONSE';
export const LISTA_DEVICE_OWNER_FAILED = 'LISTA_DEVICE_OWNER_FAILED';

// DELETE USERS
export const DELETE_DEVICE_OWNER_REQUEST = 'DELETE_DEVICE_OWNER_REQUEST';
export const DELETE_DEVICE_OWNER_RESPONSE = 'DELETE_DEVICE_OWNER_RESPONSE';
export const DELETE_DEVICE_OWNER_FAILED = 'DELETE_DEVICE_OWNER_FAILED';