// SETEAR USERS
export const SET_GPS_REQUEST = 'SET_GPS_REQUEST';
// CREATE USERS
export const CREATE_GPS_REQUEST = 'CREATE_GPS_REQUEST';
export const CREATE_GPS_RESPONSE = 'CREATE_GPS_RESPONSE';
export const CREATE_GPS_FAILED = 'CREATE_GPS_FAILED';

// UPDATE USERS
export const UPDATE_GPS_REQUEST = 'UPDATE_GPS_REQUEST';
export const UPDATE_GPS_RESPONSE = 'UPDATE_GPS_RESPONSE';
export const UPDATE_GPS_FAILED = 'UPDATE_GPS_FAILED';