// LISTA USERS
export const LISTA_USERS_REQUEST = 'LISTA_USERS_REQUEST';
export const LISTA_USERS_RESPONSE = 'LISTA_USERS_RESPONSE';
export const LISTA_USERS_FAILED = 'LISTA_USERS_FAILED';

// DELETE USERS
export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST';
export const DELETE_USERS_RESPONSE = 'DELETE_USERS_RESPONSE';
export const DELETE_USERS_FAILED = 'DELETE_USERS_FAILED';