// LISTA USERS
export const LISTA_GPS_REQUEST = 'LISTA_GPS_REQUEST';
export const LISTA_GPS_RESPONSE = 'LISTA_GPS_RESPONSE';
export const LISTA_GPS_FAILED = 'LISTA_GPS_FAILED';

// DELETE USERS
export const DELETE_GPS_REQUEST = 'DELETE_GPS_REQUEST';
export const DELETE_GPS_RESPONSE = 'DELETE_GPS_RESPONSE';
export const DELETE_GPS_FAILED = 'DELETE_GPS_FAILED';