// SETEAR USERS
export const SET_OWNER_REQUEST = 'SET_OWNER_REQUEST';
// CREATE USERS
export const CREATE_OWNER_REQUEST = 'CREATE_OWNER_REQUEST';
export const CREATE_OWNER_RESPONSE = 'CREATE_OWNER_RESPONSE';
export const CREATE_OWNER_FAILED = 'CREATE_OWNER_FAILED';

// UPDATE USERS
export const UPDATE_OWNER_REQUEST = 'UPDATE_OWNER_REQUEST';
export const UPDATE_OWNER_RESPONSE = 'UPDATE_OWNER_RESPONSE';
export const UPDATE_OWNER_FAILED = 'UPDATE_OWNER_FAILED';