// SETEAR USERS
export const SET_USERS_REQUEST = 'SET_USERS_REQUEST';
// CREATE USERS
export const CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST';
export const CREATE_USERS_RESPONSE = 'CREATE_USERS_RESPONSE';
export const CREATE_USERS_FAILED = 'CREATE_USERS_FAILED';

// UPDATE USERS
export const UPDATE_USERS_REQUEST = 'UPDATE_USERS_REQUEST';
export const UPDATE_USERS_RESPONSE = 'UPDATE_USERS_RESPONSE';
export const UPDATE_USERS_FAILED = 'UPDATE_USERS_FAILED';