// LISTA USERS
export const LISTA_ROL_REQUEST = 'LISTA_ROL_REQUEST';
export const LISTA_ROL_RESPONSE = 'LISTA_ROL_RESPONSE';
export const LISTA_ROL_FAILED = 'LISTA_ROL_FAILED';

// DELETE USERS
export const DELETE_ROL_REQUEST = 'DELETE_ROL_REQUEST';
export const DELETE_ROL_RESPONSE = 'DELETE_ROL_RESPONSE';
export const DELETE_ROL_FAILED = 'DELETE_ROL_FAILED';