// LISTA USERS
export const LISTA_USER_OWNER_REQUEST = 'LISTA_USER_OWNER_REQUEST';
export const LISTA_USER_OWNER_RESPONSE = 'LISTA_USER_OWNER_RESPONSE';
export const LISTA_USER_OWNER_FAILED = 'LISTA_USER_OWNER_FAILED';

// DELETE USERS
export const DELETE_USER_OWNER_REQUEST = 'DELETE_USER_OWNER_REQUEST';
export const DELETE_USER_OWNER_RESPONSE = 'DELETE_USER_OWNER_RESPONSE';
export const DELETE_USER_OWNER_FAILED = 'DELETE_USER_OWNER_FAILED';