// LISTA USERS
export const LISTA_OWNER_REQUEST = 'LISTA_OWNER_REQUEST';
export const LISTA_OWNER_RESPONSE = 'LISTA_OWNER_RESPONSE';
export const LISTA_OWNER_FAILED = 'LISTA_OWNER_FAILED';

// DELETE USERS
export const DELETE_OWNER_REQUEST = 'DELETE_OWNER_REQUEST';
export const DELETE_OWNER_RESPONSE = 'DELETE_OWNER_RESPONSE';
export const DELETE_OWNER_FAILED = 'DELETE_OWNER_FAILED';