// SETEAR USERS
export const SET_USER_OWNER_REQUEST = 'SET_USER_OWNER_REQUEST';
// CREATE USERS
export const CREATE_USER_OWNER_REQUEST = 'CREATE_USER_OWNER_REQUEST';
export const CREATE_USER_OWNER_RESPONSE = 'CREATE_USER_OWNER_RESPONSE';
export const CREATE_USER_OWNER_FAILED = 'CREATE_USER_OWNER_FAILED';

// UPDATE USERS
export const UPDATE_USER_OWNER_REQUEST = 'UPDATE_USER_OWNER_REQUEST';
export const UPDATE_USER_OWNER_RESPONSE = 'UPDATE_USER_OWNER_RESPONSE';
export const UPDATE_USER_OWNER_FAILED = 'UPDATE_USER_OWNER_FAILED';