// SETEAR USERS
export const SET_DEVICE_OWNER_REQUEST = 'SET_DEVICE_OWNER_REQUEST';
// CREATE USERS
export const CREATE_DEVICE_OWNER_REQUEST = 'CREATE_DEVICE_OWNER_REQUEST';
export const CREATE_DEVICE_OWNER_RESPONSE = 'CREATE_DEVICE_OWNER_RESPONSE';
export const CREATE_DEVICE_OWNER_FAILED = 'CREATE_DEVICE_OWNER_FAILED';

// UPDATE USERS
export const UPDATE_DEVICE_OWNER_REQUEST = 'UPDATE_DEVICE_OWNER_REQUEST';
export const UPDATE_DEVICE_OWNER_RESPONSE = 'UPDATE_DEVICE_OWNER_RESPONSE';
export const UPDATE_DEVICE_OWNER_FAILED = 'UPDATE_DEVICE_OWNER_FAILED';